description: This step performs a security check for Cross-Origin Resource Sharing (CORS) misconfigurations on the specified target site. It utilizes 'gau' to gather URLs from the target, then curls each URL with a custom Origin header set to 'https://evil.com'. If the response includes this origin, indicating a potential CORS vulnerability, the URL is echoed with a "Potential CORS Found" message. Otherwise, it reports no issue found with the specific URL. This script is essential for identifying and mitigating security vulnerabilities related to improper CORS settings.
tags: cors, security, pentest, curl
params: target=testphp.vulnweb.com
env:
  - HOME: /root/
  - LOG_DIR: ${HOME}/logs
  - PATH: /usr/local/bin:${PATH}
steps:
  - name: CORS
    command: bash
    script: |
      site=$target; gau "$site" | while read url; do target=$(curl -sIH "Origin: https://evil.com" -X GET $url) | if grep 'https://evil.com'; then [Potentional CORS Found] echo $url; else echo Nothing on "$url"; fi; done
