description: This YAML searches misconfigurations for a given domain with Nuclei templates.
tags: nuclei, misconfiguration
params: target=http://vulnweb.com header="Example:Blackdagger"
steps:
  - name: MisconfigScan
    command: bash
    script: |
      nuclei -t http/misconfiguration -target $target -H $header