description: Searches misconfigurations for a given domain and it's subdomains.
tags: misconfig, misconfiguration
params: target=vulnweb.com header="Example:Blackdagger"
# Change header without blank if you need or add authorization
env:
  - HOME: /root/
  - LOG_DIR: ${HOME}/logs
  - PATH: /usr/local/bin:${PATH}
steps:
  - name: MisconfigScan
    command: bash
    script: |
      httpx -u $target -retries 5 | nuclei -t http/misconfiguration -nh -H ${header//\"}